### ISSUE TITLE
Output meaning

### ISSUE THREAD

**Issue by djsb** [Scdales/Arbicoin#1]
Hi,

Can you ellaborate a little on the meaning of the output?

This array?
ETHBTC
[[16.80773198069916, 'BTCE'], [16.80672551373538, 'POLONIEX'], [16.754909188392197, 'BITFINEX'], [16.75325306291349, 'BITTREX'], [16.74817444898506, 'KRAKEN'], [16.593931753714, 'LIVECOIN']]

And these?
BTCE = 0.995353887897
KRAKEN = 0.99703895864
POLONIEX = 0.998380130879
BITTREX = 0.998798714641
BITFINEX = 0.996631275528
LIVECOIN = 1.00006005285

**Comment by Scdales** [comment]
Hi!

Apologies for not being clearer, I will update the readme following this.

The program assumes a single bitcoin is used to make an initial purchase (for testing purposes). The first set of results are the amount of cryptocoins you'll receive for 1 Bitcoin on each respective site.

The second set of results lists the amount of bitcoin you'll receive if that amount of crypto (in this case ETC) is traded back to BTC on each respective site.

As you can see, most come out at a loss, and do not even cover the transaction fees. Transaction time has yet to be factored in also.

Hope this answers your question.
